### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by manuelagard** [silverprize/materialdrive#2]
Very nice job !
I really would like to use it in my web app, but is there any documentation ?
That would be a great time saving !

**Comment by silverprize** [comment]
@manuelagard Hi.:grinning: 
What specific information do you need?
I seems to be available from next weekend.

**Comment by manuelagard** [comment]
Great ! thank you for your answer.
I just would like to know how to implement this.
Is there any directive I can use to do the thing ?
How to implement Oauth2 ? etc...

**Comment by silverprize** [comment]
@manuelagard Sorry for late.
I've started to write. You can see the pages at wiki.
I wrote the following three.
[wiki/Context-menu](../wiki/Context-menu)
[wiki/Sign-in](../wiki/Sign-in)
[wiki/File-navigation](../wiki/File-navigation)

I will write one by one when the time. When all of pages be done, will close this issue.

**Comment by manuelagard** [comment]
Great, thanks !
+1

**Comment by silverprize** [comment]
Documentation has been completed. Please check it Wiki.
If there is not enough? Feel free to ask me questions.
